<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard Report - {{ $churchName }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #333;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 24px;
        }

        .header h1 {
            font-size: 18pt;
            font-weight: bold;
            margin: 0 0 4px 0;
            color: #333;
        }

        .header h2 {
            font-size: 15pt;
            font-weight: normal;
            margin: 0 0 16px 0;
            color: #555;
        }

        .meta {
            font-size: 10px;
            color: #666;
            margin-bottom: 4px;
        }

        .section-title {
            font-size: 14pt;
            font-weight: bold;
            color: #8c52ff;
            margin: 20px 0 12px 0;
            text-align: center;
        }

        .subsection-title {
            font-size: 12pt;
            font-weight: bold;
            color: #333;
            margin: 16px 0 10px 0;
        }

        table.filters-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.filters-table td {
            padding: 6px 10px;
            border: 1px solid #ddd;
            vertical-align: top;
        }

        table.filters-table td.label {
            width: 25%;
            background-color: #8c52ff;
            color: white;
            font-weight: bold;
            font-size: 10px;
        }

        table.filters-table td.value {
            width: 25%;
            font-size: 10px;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 12px 0;
        }

        table.data-table th {
            background-color: #804180;
            color: white;
            padding: 8px 10px;
            font-size: 10px;
            font-weight: bold;
            text-align: left;
        }

        table.data-table td {
            padding: 6px 10px;
            border: 1px solid #ddd;
            font-size: 10px;
        }

        table.data-table tr:nth-child(even) td {
            background-color: #f9f5ff;
        }

        .chart-wrapper {
            text-align: center;
            margin: 16px 0;
        }

        .chart-wrapper img {
            max-width: 480px;
        }

        .summary-box {
            border: 1px solid #8c52ff;
            border-radius: 4px;
            padding: 16px;
            margin: 16px 0;
            text-align: center;
        }

        .summary-box .count {
            font-size: 24pt;
            font-weight: bold;
            color: #8c52ff;
        }

        .summary-box .label {
            font-size: 11px;
            color: #666;
        }

        .bullet-item {
            padding: 2px 0;
            font-size: 10px;
        }

        .no-data {
            text-align: center;
            padding: 24px;
            color: #999;
            font-style: italic;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 9px;
            color: #999;
            text-align: center;
            border-top: 1px solid #eee;
            padding: 4px;
        }

        .page-break {
            page-break-before: always;
        }

        .detail-title {
            font-size: 13pt;
            font-weight: bold;
            color: #8c52ff;
            margin-bottom: 12px;
        }
    </style>
</head>
<body>

    <!-- ============ PAGE 1: HEADER & SUMMARY ============ -->
    <div class="header">
        <h1>{{ $churchName ?? 'PERFIT' }}</h1>
        <h2>Dashboard Report</h2>
        <div class="meta">
            Report Period: {{ $startDate ? $startDate . ' - ' . ($endDate ?? 'Present') : 'All Available Data' }}
        </div>
        <div class="meta">
            Generated by: {{ $adminEmail }}
        </div>
        <div class="meta">
            Generated on: {{ $generatedAt }}
        </div>
    </div>

    <!-- Filters Section (only if at least one filter has a non-N/A value) -->
    @php
        $hasActiveFilters = collect($filters)->contains(fn($f) => isset($f['value']) && $f['value'] !== '' && $f['value'] !== 'N/A' && $f['value'] !== null);
    @endphp

    @if($hasActiveFilters)
        <div class="subsection-title">Filters Applied</div>
        <table class="filters-table">
            @foreach(array_chunk($filters, 2) as $pair)
                <tr>
                    @foreach($pair as $filter)
                        <td class="label">{{ $filter['title'] ?? '' }}</td>
                        <td class="value">{{ $filter['value'] ?? 'N/A' }}</td>
                    @endforeach
                    @if(count($pair) === 1)
                        <td class="label"></td>
                        <td class="value"></td>
                    @endif
                </tr>
            @endforeach
        </table>
    @endif

    <!-- Summary -->
    <div class="subsection-title">Summary of Test Participants</div>
    <div class="summary-box">
        <div class="count">{{ $totalTakers }}</div>
        <div class="label">Total Test Takers</div>
    </div>

    <!-- ============ CHART SECTIONS ============ -->
    @php
        $chartSections = [
            ['key' => 'gender',  'title' => 'Gender Distribution'],
            ['key' => 'age',     'title' => 'Age Distribution'],
            ['key' => 'baptized','title' => 'Baptism Status'],
            ['key' => 'faith',   'title' => 'Time in Faith'],
            ['key' => 'skills',  'title' => 'Skills Assessment'],
            ['key' => 'ministry','title' => 'Ministry Preferences'],
            ['key' => 'marital', 'title' => 'Marital Status'],
        ];
    @endphp

    @foreach($chartSections as $section)
        @php
            $key = $section['key'];
            $hasData = !empty($chartData[$key]) && is_array($chartData[$key]) && array_sum($chartData[$key]) > 0;
        @endphp

        @if($hasData)
            <div class="page-break">
                <div class="section-title">{{ $section['title'] }}</div>

                @if(!empty($chartImages[$key]))
                    <div class="chart-wrapper">
                        <img src="{{ Storage::disk('local')->path($chartImages[$key]) }}" width="480">
                    </div>
                @endif

                <table class="data-table">
                    <tr>
                        <th style="width:50%;">Category</th>
                        <th style="width:50%;">Count</th>
                    </tr>
                    @foreach($chartData[$key] as $category => $count)
                        @if($count > 0)
                            <tr>
                                <td>{{ $category }}</td>
                                <td>{{ $count }}</td>
                            </tr>
                        @endif
                    @endforeach
                </table>
            </div>
        @endif
    @endforeach

    <!-- ============ FINAL PAGE: DETAILED USER TABLE ============ -->
    <div class="page-break">
        <div class="detail-title">Detailed Report of Users Including Contact and Ministry Eligibility</div>

        @if(count($tableRows) > 0)
            <table class="data-table">
                <thead>
                    <tr>
                        <th style="width:20%;">Name</th>
                        <th style="width:25%;">Email</th>
                        <th style="width:55%;">Eligible Ministries</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tableRows as $row)
                        <tr>
                            <td>{{ $row['name'] ?? '' }}</td>
                            <td>{{ $row['email'] ?? '' }}</td>
                            <td>
                                @if(!empty($row['eligible_ministries']) && is_array($row['eligible_ministries']))
                                    @foreach($row['eligible_ministries'] as $ministry)
                                        &bull; {{ $ministry }}<br>
                                    @endforeach
                                @else
                                    <span style="color:#999;font-style:italic;">N/A</span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <div class="no-data">No records match the current filter criteria.</div>
        @endif
    </div>

    <!-- ============ FOOTER ============ -->
    <div class="footer">
        Generated by: {{ $adminEmail }} &nbsp;&nbsp;&nbsp; Generated on: {{ \Carbon\Carbon::parse($generatedAt)->format('Y-m-d') }}
    </div>

</body>
</html>

<script type="text/php">
    $font = $fontMetrics->getFont('DejaVu Sans');
    $w = $pdf->get_width();
    $h = $pdf->get_height();
    $pdf->page_text($w - 100, $h - 18, "Page $PAGE_NUM of $PAGE_COUNT", $font, 8, [0.6, 0.6, 0.6]);
</script>